# 1. Install dependencies only when needed
FROM node:22-alpine AS deps
WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# 2. Rebuild the source code only when needed
FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm

ARG  DATABASE_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG GLITHUB_CLIENT_ID
ARG GLITHUB_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG POSTGRES_DB
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG RABBITMQ_URL
ARG RABBITMQ_EXCHANGE
ARG RABBITMQ_EXCHANGETYPE
ARG RABBITMQ_QUEUE
ARG RABBITMQ_ROUTING_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV GLITHUB_CLIENT_ID=$GLITHUB_CLIENT_ID
ENV GLITHUB_CLIENT_SECRET=$GLITHUB_CLIENT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV RABBITMQ_URL=$RABBITMQ_URL
ENV RABBITMQ_EXCHANGE=$RABBITMQ_EXCHANGE
ENV RABBITMQ_EXCHANGETYPE=$RABBITMQ_EXCHANGETYPE
ENV RABBITMQ_QUEUE=$RABBITMQ_QUEUE
ENV RABBITMQ_ROUTING_KEY=$RABBITMQ_ROUTING_KEY

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

# 3. Production image, copy all the files and run nextjs
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
RUN npm install -g pnpm

ARG  DATABASE_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG GLITHUB_CLIENT_ID
ARG GLITHUB_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG POSTGRES_DB
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG RABBITMQ_URL
ARG RABBITMQ_EXCHANGE
ARG RABBITMQ_EXCHANGETYPE
ARG RABBITMQ_QUEUE
ARG RABBITMQ_ROUTING_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV GLITHUB_CLIENT_ID=$GLITHUB_CLIENT_ID
ENV GLITHUB_CLIENT_SECRET=$GLITHUB_CLIENT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV RABBITMQ_URL=$RABBITMQ_URL
ENV RABBITMQ_EXCHANGE=$RABBITMQ_EXCHANGE
ENV RABBITMQ_EXCHANGETYPE=$RABBITMQ_EXCHANGETYPE
ENV RABBITMQ_QUEUE=$RABBITMQ_QUEUE
ENV RABBITMQ_ROUTING_KEY=$RABBITMQ_ROUTING_KEY

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["pnpm", "start"]