version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .local.env
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  pgdata:
