# .github/workflows/docker-build.yml

name: Build and Push Docker Image

# This workflow runs on every push to the 'main' or 'Auth' branch
on:
  push:
    branches: ["main", "Auth"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Example step: Login to a Docker registry (e.g., Docker Hub)
      # You would also need to add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to your repo secrets
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker-compose build
        # We pass the secrets from GitHub to the environment of the 'run' step
        # docker-compose will automatically pick them up if configured to do so
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Run tests as an example step
        run: echo "Image built successfully. You could run tests here."

      # Example step: Push the image if the build is successful
      # - name: Push the Docker image
      #   run: docker-compose push