name: Publish Docker image

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/distcode
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy
            RABBITMQ_URL=amqp://dummy
            NEXTAUTH_SECRET=dummy-build-secret
            NEXTAUTH_URL=http://localhost:3000
            GOOGLE_CLIENT_ID=dummy
            GOOGLE_CLIENT_SECRET=dummy
            GITHUB_CLIENT_ID=dummy
            GITHUB_CLIENT_SECRET=dummy